---
- name: Installing all the necessary parts
  hosts: target
  become: yes
  tasks:
  - name: Install EPEL repository
    yum:
      name: epel-release
      state: latest
  - name: Install Python pip
    yum:
      name: python-pip
  - name: Upgraade pip
    pip:
     name: pip
     extra_args: --upgrade
  - name: Install Docker module for Python
    pip:
      name: docker
      state: latest
  - name: Install Docker Compose module
    pip:
      name: docker-compose
      state: latest
  - name: Install jsondiff
    pip:
      name: jsondiff
      state: latest
  - name: Install Git
    yum:
      name: git
      state: latest
  - name: Clone the app repo
    git:
      repo: 'https://github.com/yohannafrans/secondphasefinalproject'
      dest: /root/secondphasefinalproject
      version: master